version: "3"

services:
  orai:
    image: orai/orai:0.40.4-ibc-alpine
    container_name: orai_local
    working_dir: /root
    tty: true
    volumes:
      - ./config:/root/.oraid/config
      - ./data/:/root/.oraid/data/
      - ./keyring-test:/root/.oraid/keyring-test
    networks:
      - orai
    ports:
      - "26656:26656"
      - "26657:26657"
      - "1317:1317"
      - "9090:9090"
      - "9091:9091"
    command: oraid start --home /root/.oraid

networks:
  orai:
    driver: bridge
